/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Main;
import Model.Data;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class Mainframe extends javax.swing.JFrame {

    private Main main;
    private ArrayList<Data> data; 
    
    public Mainframe(Main main) {
        initComponents();
        this.main = main;
        this.data = new ArrayList<Data>();
    }

    private Mainframe() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pengaturanpreferensi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dashboard = new javax.swing.JPanel();
        Data = new javax.swing.JPanel();
        tittle_data = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabel_data = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_calon_penerima_bantuan = new javax.swing.JTable();
        buton_data = new javax.swing.JPanel();
        muat_data = new javax.swing.JButton();
        Hasil = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_rangking = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        mulai_perangkingan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tugas Akhir Dea");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setText("Sistem Pendukung");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Multi Factor Evaluation Process");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("- Weighted Product");

        pengaturanpreferensi.setText("Preferensi");
        pengaturanpreferensi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengaturanpreferensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengaturanpreferensiActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel6.setText("Keputusan");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pengaturanpreferensi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengaturanpreferensi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", home);

        dashboard.setLayout(new javax.swing.BoxLayout(dashboard, javax.swing.BoxLayout.LINE_AXIS));

        Data.setPreferredSize(new java.awt.Dimension(500, 541));
        Data.setLayout(new javax.swing.BoxLayout(Data, javax.swing.BoxLayout.PAGE_AXIS));

        tittle_data.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tittle_data.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Data Calon Penerima Bantuan");

        javax.swing.GroupLayout tittle_dataLayout = new javax.swing.GroupLayout(tittle_data);
        tittle_data.setLayout(tittle_dataLayout);
        tittle_dataLayout.setHorizontalGroup(
            tittle_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tittle_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        tittle_dataLayout.setVerticalGroup(
            tittle_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tittle_dataLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Data.add(tittle_data);

        tabel_data.setPreferredSize(new java.awt.Dimension(700, 166));
        tabel_data.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        table_calon_penerima_bantuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Pekerjaan", "Penghasilan", "Tanggungan", "Kondisi Rumah", "Kepemilikan Rumah", "Jaringan Listrik", "Jenis Rumah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_calon_penerima_bantuan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(table_calon_penerima_bantuan);
        if (table_calon_penerima_bantuan.getColumnModel().getColumnCount() > 0) {
            table_calon_penerima_bantuan.getColumnModel().getColumn(0).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(1).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(2).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(3).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(4).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(5).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(6).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(7).setMinWidth(130);
            table_calon_penerima_bantuan.getColumnModel().getColumn(8).setMinWidth(130);
        }

        tabel_data.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Data.add(tabel_data);

        buton_data.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        buton_data.setPreferredSize(new java.awt.Dimension(422, 50));
        buton_data.setLayout(new java.awt.BorderLayout());

        muat_data.setText("Muat Data");
        muat_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        muat_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muat_dataActionPerformed(evt);
            }
        });
        buton_data.add(muat_data, java.awt.BorderLayout.CENTER);

        Data.add(buton_data);

        dashboard.add(Data);

        Hasil.setBackground(new java.awt.Color(0, 0, 204));
        Hasil.setPreferredSize(new java.awt.Dimension(500, 541));
        Hasil.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Hasil Perangkingan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(390, 166));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabel_rangking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "MFEP", "WP"
            }
        ));
        jScrollPane2.setViewportView(tabel_rangking);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));

        mulai_perangkingan.setText("Mulai Perangkingan");
        mulai_perangkingan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulai_perangkingan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulai_perangkinganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(mulai_perangkingan, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mulai_perangkingan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        Hasil.add(jPanel2, java.awt.BorderLayout.CENTER);

        dashboard.add(Hasil);

        jTabbedPane1.addTab("Dashboard", dashboard);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pengaturanpreferensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengaturanpreferensiActionPerformed
        this.main.tampilkanFramePreferensi();
    }//GEN-LAST:event_pengaturanpreferensiActionPerformed

    private void muat_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muat_dataActionPerformed
        try {
            this.data = this.main.muatData(this.jPanel1);
            if(this.data.size() > 0){
               DefaultTableModel tabel = (DefaultTableModel) this.tabel_rangking.getModel();
               tabel.setRowCount(this.data.size());
               this.setDataCalonPenerimaBantuanKeTabel(this.data);   
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_muat_dataActionPerformed

    private void mulai_perangkinganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulai_perangkinganActionPerformed
        ArrayList<Data> mfep = this.main.mulai_SPK_MFEP(this.data);
        if(mfep != null){
            this.setTabelRangkingMFEP(mfep);
            this.setTabelRangkingWP(this.main.mulai_SPK_WP(data));
        }
    }//GEN-LAST:event_mulai_perangkinganActionPerformed

    private void setDataCalonPenerimaBantuanKeTabel(ArrayList<Data> cp){
        DefaultTableModel tabel = (DefaultTableModel) this.table_calon_penerima_bantuan.getModel();
        tabel.setRowCount(0);
        tabel.setColumnCount(cp.get(0).getKriteria_pada_data().size()+2); //satu lagi untuk nama dan nomor
        Object[] obj;
        int index,nomor=1;
        for(Data orang : cp){
            obj = new Object[tabel.getColumnCount()];
            obj[0] = nomor;
            obj[1] = orang.getNama();
            index = 2;
            for(int i=0;i<orang.getKriteria_pada_data().size();i++){
               obj[index] = orang.getKriteria_pada_data().get(i);
               index++;
            }
            nomor++;
            tabel.addRow(obj);
        }
    }
    
    private void setTabelRangkingMFEP(ArrayList<Data> mfep){
         DefaultTableModel tabel = (DefaultTableModel) this.tabel_rangking.getModel();
         int kolom = 1;
         for(int i=0;i<mfep.size();i++){
             tabel.setValueAt((i+1), i, 0); //nomor
             tabel.setValueAt(mfep.get(i).getNama(), i, kolom);
         }
    }
    
     private void setTabelRangkingWP(ArrayList<Data> wp){
         DefaultTableModel tabel = (DefaultTableModel) this.tabel_rangking.getModel();
         int kolom = 2;
         for(int i=0;i<wp.size();i++){
             tabel.setValueAt(wp.get(i).getNama(), i, kolom);
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Hasil;
    private javax.swing.JPanel buton_data;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton muat_data;
    private javax.swing.JButton mulai_perangkingan;
    private javax.swing.JButton pengaturanpreferensi;
    private javax.swing.JPanel tabel_data;
    private javax.swing.JTable tabel_rangking;
    private javax.swing.JTable table_calon_penerima_bantuan;
    private javax.swing.JPanel tittle_data;
    // End of variables declaration//GEN-END:variables
}
