/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Kriteria;
import Model.Nilai_Faktor;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class Pengaturan extends javax.swing.JFrame {

    private ArrayList<Kriteria> kriteria;
    
    public Pengaturan(ArrayList<Kriteria> kriteria) {
        initComponents();
        this.kriteria = kriteria;
        this.setDataToList(0);
        this.setNilaiKriteria(this.kriteria.get(0));
        this.setKondisiKriteria(this.kriteria.get(0));
        this.setTabelFaktor(this.kriteria.get(0));
    }

    private Pengaturan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void setDataToList(int index){
       DefaultListModel listModel = new DefaultListModel();
       for(Kriteria k : this.kriteria){
           listModel.addElement(k.getNama());
       }    
       this.list_kriteria.setModel(listModel);
       this.list_kriteria.setSelectedIndex(index);
    }
    
    private void setNilaiKriteria(Kriteria k){
        this.nilai_kriteria.setValue(k.getNilai());
    }
    
    private void setKondisiKriteria(Kriteria k){
        int index = 0;
        switch(k.getKondisi()){
            case "Cost(-)" : index = 1; break;
            case "Benefit(+)" : index = 0; break;
        }
        this.kondisi_kriteria.setSelectedIndex(index);
    }
    
    private void setTabelFaktor(Kriteria k){
        DefaultTableModel model = (DefaultTableModel)this.tabel_faktor.getModel();
        model.setRowCount(0);
        Object[] object;
        for(Nilai_Faktor f : k.getFaktor()){
           object = new Object[2];  
           object[0] = f.getNama();
           object[1] = f.getNilai();
           model.addRow(object);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_kriteria = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nilai_kriteria = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        kondisi_kriteria = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kriteria_label = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_faktor = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kriteria Preferensi");
        setPreferredSize(new java.awt.Dimension(800, 530));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 428));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setPreferredSize(new java.awt.Dimension(256, 5));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel15.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel15.setPreferredSize(new java.awt.Dimension(252, 20));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Kriteria");
        jPanel15.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel3.add(jPanel7);

        jPanel4.setPreferredSize(new java.awt.Dimension(35, 300));
        jPanel4.setLayout(new java.awt.BorderLayout());

        list_kriteria.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_kriteria.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_kriteriaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_kriteria);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(256, 50));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setPreferredSize(new java.awt.Dimension(256, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setMaximumSize(new java.awt.Dimension(50, 32767));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 93));

        jLabel1.setText("Nilai Kriteria");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel13);
        jPanel11.add(nilai_kriteria);

        jPanel9.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9);

        jPanel8.setPreferredSize(new java.awt.Dimension(256, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        kondisi_kriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benefit(+)", "Cost(-)" }));
        kondisi_kriteria.setMaximumSize(new java.awt.Dimension(32767, 50));
        kondisi_kriteria.setPreferredSize(new java.awt.Dimension(56, 50));
        jPanel8.add(kondisi_kriteria, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        jPanel12.setPreferredSize(new java.awt.Dimension(350, 428));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(428, 65));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nilai Evaluasi Faktor");

        kriteria_label.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kriteria_label.setText("KRITERIA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kriteria_label)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kriteria_label))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel22.add(jPanel5);

        jPanel10.setPreferredSize(new java.awt.Dimension(428, 500));
        jPanel10.setLayout(new java.awt.BorderLayout());

        tabel_faktor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Faktor", "Nilai"
            }
        ));
        jScrollPane2.setViewportView(tabel_faktor);

        jPanel10.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel10);

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setPreferredSize(new java.awt.Dimension(428, 60));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23);

        jPanel14.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void list_kriteriaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_kriteriaValueChanged
        int index = this.getIndexList();
        this.kriteria_label.setText("'"+this.kriteria.get(index).getNama()+"'");
        this.setNilaiKriteria(this.kriteria.get(index));
        this.setKondisiKriteria(this.kriteria.get(index));
        this.setTabelFaktor(this.kriteria.get(index)); 
    }//GEN-LAST:event_list_kriteriaValueChanged
  
    private int getIndexList(){
        String value =  this.list_kriteria.getSelectedValue().toString();
        int index = 0,i=0;
        for(Kriteria x : this.kriteria){
           if(value.equalsIgnoreCase(x.getNama())){
               index = i;
               break;
           }
           i++;
        }
        return index;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kondisi_kriteria;
    private javax.swing.JLabel kriteria_label;
    private javax.swing.JList<String> list_kriteria;
    private javax.swing.JSpinner nilai_kriteria;
    private javax.swing.JTable tabel_faktor;
    // End of variables declaration//GEN-END:variables
}
